### ISSUE TITLE
Interactive-Haskell hangs

### ISSUE THREAD

**Issue by xificurC** [iquiw/company-ghc#10]
Hi there,
I'm not sure if this is exactly company-ghc's fault but I don't know where else to go, so feel free to point me somewhere else if needed :)
I'm working on the [scheme48hours](https://en.wikibooks.org/wiki/Write_Yourself_a_Scheme_in_48_Hours) and interactive haskell hangs on me when I start a scheme repl from within the cabal repl. I have to kill ghc and then I either see this in *Messages*

    Company: An error occurred in auto-begin
    Wrong type argument: stringp, nil

or I get 1k lines of completions shown in the haskell process log. Either way I have to kill ghc and emacs starts responding only afterwards.

Steps to reproduce (on my machine at least):

- open Main.hs in Emacs
- `C-c C-l` to load the file in the REPL
- `runRepl` to start the scheme repl
- type a letter or two and wait for the completion to kick in (and that's when it hangs)

In case you really go down testing this and want the code I have then [here](https://github.com/xificurC/scheme-interpreter) it is, the current master [0fc2d53] is the one you should clone.

To make the listing full, here are my versions:

- ghc - 7.8.3
- emacs - 24.4.1
- emacs packages - updated as of yesterday
- ghc-mod - 5.2.1.1

**Comment by xificurC** [comment]
Hi, sorry for replying so late... Indeed `M-x completion-at-point` hangs for me as well. Going to report it in haskell-mode and see what happens. Thank you for your time!

**Comment by xificurC** [comment]
[Here](https://github.com/haskell/haskell-mode/issues/416#issuecomment-68942053) is the answer I got from Chris Done if you wish to know the reasons behind this issue. Thank you for your help and feel free to mark this closed.

**Comment by iquiw** [comment]
You're welcome.
Thanks for the pointer.
