### ISSUE TITLE
ghc-boot process seems to have failed

### ISSUE THREAD

**Issue by etanter** [iquiw/company-ghc#17]
Hi,

I'm trying to get company-ghc to work, but without success. The diagnostic reports:

```
* company-ghc backend found: company-ghc
* automatic scan module is enabled
* ghc-boot process seems to have failed

Module                                  Alias               Candidates
-------------------------------------------------------------------------------
Prelude                                 -                        0
```

So I applied the recommendations:
- ghc-mod is properly installed apparently (eg. I can do completion on `inst` and it goes to `instance`)
- `ghc-mod boot` on the command line does work and gives a huge list of identifiers
- running with ghc-debug mode does not seem to reveal any issue. Here is the *GHC Debug* buffer:

```
% ghc-mod root
/Users/etanter/Develop/Haskell
% boot
% check /Users/etanter/Develop/Haskell/Arboles.hs
% check /Users/etanter/Develop/Haskell/Arboles.hs
```

I find it strange that it says `boot` above and not `ghc-mode boot`. Could it be the problem? if so, where to fix that?
If not, any idea? Something I can do to dig into the matter?

thanks!

**Comment by iquiw** [comment]
It is correct behavior that `% boot` or `% check ...` is written. However, outputs of their command should follow them when `ghc-mod` correctly works.
Did you run `ghc-mod boot` in `/Users/etanter/Develop/Haskell`? If not, please try.

**Comment by etanter** [comment]
Yes, I did do that, and it gives a huge list of identifiers, which I guess is the expected behavior.

**Comment by iquiw** [comment]
Ya, `ghc-mod boot` seems to work.
I have no idea about the cause.
I suppose it is `ghc-mod` issue (`ghc-modi` or `ghc-mod`'s elisp).

**Comment by etanter** [comment]
Thanks. If you have any further suggestion on how to identify the source of the problem, that'd be very welcome. For now I'm stuck. I installed ghc-mod and company-ghc on another machine (same Mac OS 10.10), and have exactly the same issue...

**Comment by iquiw** [comment]
Can you check if `ghc-modi` works?
```
$ /Users/etanter/Develop/Haskell
$ ghc-modi
boot
```

**Comment by etanter** [comment]
`ghc-modi` seems to work as well, as `boot` gives me a huge list of symbols.

**Comment by iquiw** [comment]
So the suspect is `ghc-mod`'s elisp.
Which version (MELPA, Hackage, etc.) of `ghc-mod` are you using?

**Comment by etanter** [comment]
I have installed emacs packages through MELPA, and haskell packages through cabal.

```
$ cabal list ghc-mod
* ghc-mod
    Synopsis: Happy Haskell Programming
    Default available version: 5.2.1.2
    Installed versions: 5.2.1.2
    Homepage: http://www.mew.org/~kazu/proj/ghc-mod/
    License:  BSD3
```

As for emacs packages:
```
ghc-20150713.400/
company-ghc-20150613.123/ 
```

Maybe a clue: when I try to run `M-x ghc-debug`, it complains that `ghc-interactive-command` is void...

**Comment by iquiw** [comment]
I got what is happening.
MELPA version of `ghc-mod` uses `legacy-interactive` argument when calling `ghc-mod` process.
It is not supported by Hackage version of `ghc-mod`.

So possible solutions are:
* Build `ghc-mod` command from github `master`.
* Use MELPA-stable version of `ghc-mod` elisp. (I am not sure it works or not.)

**Comment by etanter** [comment]
brilliant! I used the elisp from MELPA-stable and it works like a charm.

Thank you very much for your help in diagnosing and fixing this!!

**Comment by iquiw** [comment]
You are welcome :wink:
