### ISSUE TITLE
How I can stop company-ghc to inject close parenthesis on import module keyword?

### ISSUE THREAD

**Issue by ryukinix** [iquiw/company-ghc#34]
After press once `tab` I got:
![image](https://user-images.githubusercontent.com/7642878/28270721-e1b4a714-6adc-11e7-8008-c3a8ce4370b7.png)

If I try press `tab` again, again and again I got:
![image](https://user-images.githubusercontent.com/7642878/28270759-0166b4c6-6add-11e7-9819-af9546eb9a22.png)

Is a easy way to not insert the closing parenthesis? Where on the source this is done?

**Comment by ryukinix** [comment]
This is bad for me mainly because I use smartparens, so always when I open a parenthesis on module import it is closed automatically... Then I press `tab` and company injects a new parenthesis...

**Comment by iquiw** [comment]
I confirmed this happens without `company-ghc` (below with `company-dabbrev`). I saw the same even in `c-mode`.
![image](https://user-images.githubusercontent.com/238681/28318702-aded6f62-6c06-11e7-9695-95cd54fa9b08.png)

Maybe related. https://github.com/Fuco1/smartparens/issues/445

**Comment by ryukinix** [comment]
What hell... Well, thanks for found the reason! Really weird.

**Comment by ryukinix** [comment]
Closed due lack of activity (> year 1).
