### ISSUE TITLE
company-ghc backend found: company-ghc but ghc-boot process has not been done

### ISSUE THREAD

**Issue by FirstLoveLife** [iquiw/company-ghc#37]
```
* company-ghc backend found: company-ghc
* automatic scan module is enabled
* ghc-boot process has not been done

Module                                  Alias               Candidates
-------------------------------------------------------------------------------
Prelude                                 -                        nil
```

As the diag above, though company-ghc is added to backend, ghc-boot process cannot been done. What should I do?

My config:
```
(add-to-list 'company-backends 'company-ghc)
(set-company-backend! 'haskell-mode
  'company-ghc)
  (add-hook 'haskell-mode-hook 'eglot-ensure)
```

**Comment by iquiw** [comment]
`company-ghc` assumes one already setup `ghc-mod`. See [ghc-mod wiki Frontend](https://github.com/DanielG/ghc-mod/wiki/Frontend).

I don't use `eglot`, so I am not sure, but if you are using `eglot`, I suppose you don't need `company-ghc`.

**Comment by FirstLoveLife** [comment]
Thanks for reply, I didn't setup ghc-mod indeed. I have remove company-ghc from backend, now eglot works fine with haskell language server and completion has no problem
