### ISSUE TITLE
nil and 0 candidates

### ISSUE THREAD

**Issue by MichaelXavier** [iquiw/company-ghc#5]
Hi!

I've been unable to successfully use company-ghci. Running
`company-ghc-diagnose` shows nil and 0 completions:

```
company-ghc backend found: company-ghc
automatic scan module is enabled

Module                                  Alias               Candidates
-------------------------------------------------------------------------------
Seraph.Types                            -                        nil
Debug.Trace                             -                        nil
MVC                                     -                        nil
Data.Set                                S                        nil
Data.Maybe                              -                        0
Data.Map                                M                        nil
Control.Monad.Writer.Strict             -                        nil
Control.Monad.State.Strict              -                        nil
Control.Lens                            -                        nil
Prelude                                 -                        0
```

Before you invite me to RTFM, I have read the troubleshooting steps on
this: `M-: (setq ghc-debug t)` and then `M-x ghc-debug`. Nothing jumps
out me as erroneous:

```
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
% ghc-mod version
ghc-mod version 5.0.1 compiled by GHC 7.8.3
% ghc-modi version
ghc-modi version 5.0.1 compiled by GHC 7.8.3
```

I'm using flycheck-haskell and haskell-mode. I'm happy to provide any
additional details you find necessary and thankk you in advance for
any help you can provide with debugging.

**Comment by razvan-panda** [comment]
@iquiw Having the same problem. Reading about this: http://stackoverflow.com/a/28049104/750216 I downgraded `cabal-install` to `1.20.0.6` and rebuilt the packages but that did not solve the problem. I will try upgrading to GHC 7.10.1, maybe that solves the problem.

**Comment by razvan-panda** [comment]
ghc-mod does not build with 7.10.1 yet https://github.com/kazu-yamamoto/ghc-mod/issues/437

**Comment by iquiw** [comment]
@razvan-panda It is probably `ghc-mod` issue.

ghc-mod#437 is marked as "Fixed in master", so you can install it from github.
